[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
attestation_registry = "86MykibNZvSLLZWj5jDg7gXViaqMANMeuUauP32xn8sq"
loans_marketplace = "5CsJHgdh6jtKRVJiJL4bBpTeUcUFV3B9gphEccyvGQmS"
reputation = "6uLcVgj2viBHA5niMsXvKHuxMVvTRFjvgRrD933L8pk3"
score_attestor = "5xsKPzfNAZz7bxpPLFLhWwb7QaZ9ueNuos6Hr3WMh8S5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
